use serde::Serialize;

use crate::app::{AppLanguage, text_for};

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct WebStrings {
    language: &'static str,
    open_documents: &'static str,
    move_through_tabs: &'static str,
    move_tabs_backward: &'static str,
    move_tabs_forward: &'static str,
    new_document: &'static str,
    close_document: &'static str,
    find_in_document: &'static str,
    results_zero: &'static str,
    results_one: &'static str,
    results_many: &'static str,
    replace_with: &'static str,
    previous: &'static str,
    next: &'static str,
    replace: &'static str,
    replace_all: &'static str,
    close: &'static str,
    no_document: &'static str,
    empty_description: &'static str,
    markdown_editor: &'static str,
    document_outline: &'static str,
    outline: &'static str,
    close_outline: &'static str,
    document_headings: &'static str,
    no_headings: &'static str,
    untitled_heading: &'static str,
    about: &'static str,
    close_about: &'static str,
    version: &'static str,
    author: &'static str,
    build: &'static str,
    copy: &'static str,
    copied: &'static str,
    failed: &'static str,
    about_footer: &'static str,
    ready: &'static str,
    no_document_error: &'static str,
    rendering_diagram: &'static str,
    diagram_failed: &'static str,
    rendering_formula: &'static str,
    formula_failed: &'static str,
    image_failed: &'static str,
    alert_note: &'static str,
    alert_tip: &'static str,
    alert_important: &'static str,
    alert_warning: &'static str,
    alert_caution: &'static str,
}

impl WebStrings {
    pub(crate) fn for_language(language: AppLanguage) -> Self {
        let t = |key| text_for(language, key);
        Self {
            language: language.key(),
            open_documents: t("web.open_documents"),
            move_through_tabs: t("web.move_through_tabs"),
            move_tabs_backward: t("web.move_tabs_backward"),
            move_tabs_forward: t("web.move_tabs_forward"),
            new_document: t("web.new_document"),
            close_document: t("web.close_document"),
            find_in_document: t("web.find_in_document"),
            results_zero: t("web.results_zero"),
            results_one: t("web.results_one"),
            results_many: t("web.results_many"),
            replace_with: t("web.replace_with"),
            previous: t("web.previous"),
            next: t("web.next"),
            replace: t("web.replace"),
            replace_all: t("web.replace_all"),
            close: t("web.close"),
            no_document: t("web.no_document"),
            empty_description: t("web.empty_description"),
            markdown_editor: t("web.markdown_editor"),
            document_outline: t("web.document_outline"),
            outline: t("web.outline"),
            close_outline: t("web.close_outline"),
            document_headings: t("web.document_headings"),
            no_headings: t("web.no_headings"),
            untitled_heading: t("web.untitled_heading"),
            about: t("web.about"),
            close_about: t("web.close_about"),
            version: t("web.version"),
            author: t("web.author"),
            build: t("web.build"),
            copy: t("web.copy"),
            copied: t("web.copied"),
            failed: t("web.failed"),
            about_footer: t("web.about_footer"),
            ready: t("web.ready"),
            no_document_error: t("web.no_document_error"),
            rendering_diagram: t("web.rendering_diagram"),
            diagram_failed: t("web.diagram_failed"),
            rendering_formula: t("web.rendering_formula"),
            formula_failed: t("web.formula_failed"),
            image_failed: t("web.image_failed"),
            alert_note: t("web.alert_note"),
            alert_tip: t("web.alert_tip"),
            alert_important: t("web.alert_important"),
            alert_warning: t("web.alert_warning"),
            alert_caution: t("web.alert_caution"),
        }
    }
}
